// Prime.Execute();
// Factorial.Execute();
// Fibonacci.Execute();
// Iterative.Execute();
// TwoDim.Execute();
// ThreeDim.Execute();
// MatrixClient.Execute();
// Poly.Program.Main();
// Single.Program.Main();
Score.Program.Main();
